### ISSUE TITLE
Assert statement issue in constructor of util/ExitRequest

### ISSUE THREAD

**Issue by BradWells** [nskinkel/oppy#106]
In line 21 of exitrequest.py there is an issue with the assert statement:

```
assert addr or host and not (addr and host)
```

This assertion will evaluate to (addr or host), while I believe what you want is

```
(addr or host) and ! (addr and host)
```
or more simply
```
addr ^ host
```

**Comment by nskinkel** [comment]
Yep you're right, good catch.  Tagged as a bug.

Want to make a pull request for it?

**Comment by nskinkel** [comment]
Fixed a while ago (forgot to close bug).
