### ISSUE TITLE
socks.py - Error Handling `SOCKSProtocol`

### ISSUE THREAD

**Issue by dwtj** [nskinkel/oppy#11]
I need to figure out how the protocol gets wound-down when various protocol errors occur, in particular, when malformed or unexpected messages come from the client. If nothing else, I need to add some logging when the errors are discovered. There are a few kinds of errors that may happen in the protocol's lifetime.

Also, I need to figure out how to kill the protocol if a timeout occurs.

I also remember from the SOCKS 5 RFC mentioning some context in which the SOCKS server is supposed to send a response within 10 seconds of some error occurring. I will need to look this up.

**Comment by nskinkel** [comment]
Implemented as of 508d6b9e9a
