### ISSUE TITLE
`socks.py` - SOCKS as a Twisted Service

### ISSUE THREAD

**Issue by dwtj** [nskinkel/oppy#12]
I need to figure out how to turn the current `socks.py` code into a service that can be easily started up as its own thing.

Additionally, I need to figure out how `clientRelay` and `remoteRelay` in the setup of the SOCKS service in such a way that either `EphemeralRelayPairFactory` or `SOCKSProtocol._listenOnEphemeral` can access them.

(Understanding more about these things will help when we go to create our single unified Twisted Application.)

**Comment by nskinkel** [comment]
Closing this as outdated and no longer relevant.
