### ISSUE TITLE
`socks.py` - SOCKSProxy SHOULD implement "RESOLVE_PTR"

### ISSUE THREAD

**Issue by dwtj** [nskinkel/oppy#25]
I think that, for now, the SOCKSProxy SHOULD implement "RESOLVE_PTR", but I think that it is a relatively low priority.

See `socks-extensions.txt` in the Tor specification documents for details about "RESOLVE_PTR".

**Comment by nskinkel** [comment]
This is covered in the "simplifications" documentation.
