### ISSUE TITLE
Make IP Address Representation Consistent

### ISSUE THREAD

**Issue by dwtj** [nskinkel/oppy#65]
Thoughout `Oppy`, we sometimes represent IP addresses using the `Twisted` IP address objects (e.g. `twisted.internet.address.IPv4Address`), and at other times we represent IP addresses with traditional python `ipaddress` objects.

We should settle on one or the other. I am in strong support for using standard library `ipaddress`, and only using the twisted ones when needed.

**Comment by nskinkel** [comment]
Fixed in 636ed7e425
